name: Publish VS Code extension

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  publish:
    name: Publish to Visual Studio Marketplace
    runs-on: ubuntu-latest
    env:
      VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Validate package.json publisher
        run: |
          node -e 'const p=require("./package.json"); if(!p.publisher||p.publisher==="your-publisher-name"){console.error("package.json.publisher is not set or still uses placeholder \"your-publisher-name\". Update it before publishing."); process.exit(1)} else {console.log("publisher ok:", p.publisher)}'

      - name: Ensure VSCE_TOKEN is available
        run: |
          if [ -z "$VSCE_TOKEN" ]; then
            echo "ERROR: VSCE_TOKEN is empty. Add the secret in the repo Settings → Secrets and variables → Actions with the name 'VSCE_TOKEN'."
            exit 1
          else
            echo "VSCE_TOKEN is set (masked)."
          fi

      - name: Package and publish extension
        run: |
          # Publish using vsce and the secret token
          npx vsce publish --pat $VSCE_TOKEN
        env:
          NODE_OPTIONS: --max_old_space_size=4096
